export class Sound{
 constructor(){this.enabled=true;this.ctx=null;this.clips={};this.voice=null;this.lastVoice=0;}
 async start(){if(!this.ctx){try{this.ctx=new (window.AudioContext||window.webkitAudioContext)();const c=this.ctx;this.master=c.createGain();this.master.gain.value=.4;this.master.connect(c.destination);const buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate),d=buffer.getChannelData(0);let v=0;for(let i=0;i<d.length;i++){v=(v+Math.random()*2-1)/1.025;d[i]=v*.15;}this.engine=c.createBufferSource();this.engine.buffer=buffer;this.engine.loop=true;this.filter=c.createBiquadFilter();this.filter.type='bandpass';this.filter.frequency.value=180;this.filter.Q.value=.7;this.engineGain=c.createGain();this.engineGain.gain.value=.16;this.engine.connect(this.filter).connect(this.engineGain).connect(this.master);this.engine.start();}catch{}}
  if(this.ctx?.state==='suspended')await this.ctx.resume().catch(()=>{});
 }
 tone(freq,duration=.12,volume=.08,shape='sine',end=freq){if(!this.ctx||!this.enabled)return;const c=this.ctx,o=c.createOscillator(),g=c.createGain();o.type=shape;o.frequency.setValueAtTime(freq,c.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),c.currentTime+duration);g.gain.setValueAtTime(volume,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+duration);o.connect(g).connect(this.master);o.start();o.stop(c.currentTime+duration);}
 speak(key){if(!this.enabled)return;const important=['missile','altitude','damage'].includes(key),now=Date.now();if(this.voice&&!this.voice.paused&&!important)return;if(now-this.lastVoice<950&&!important)return;this.lastVoice=now;this.voice?.pause();const a=this.clips[key]||(this.clips[key]=new Audio('audio/'+key+'.wav'));a.currentTime=0;a.volume=.86;this.voice=a;this.tone(important?880:650,.12,.09);a.play().catch(()=>{});}
 effect(type){if(type==='gun')this.tone(95,.065,.1,'sawtooth',35);if(type==='launch')this.tone(280,.45,.11,'sawtooth',65);if(type==='explosion')this.tone(75,.55,.22,'sawtooth',22);if(type==='flares')this.tone(1250,.19,.06,'triangle',160);}
 update(p,active,boost){if(!this.ctx)return;const t=this.ctx.currentTime;this.master.gain.setTargetAtTime(this.enabled?.4:0,t,.1);this.engineGain.gain.setTargetAtTime(active?(.14+p.throttle*.12+(boost?.08:0)):0,t,.12);this.filter.frequency.setTargetAtTime(110+p.speed*.5+(boost?70:0),t,.1);}
 pause(){if(this.engineGain&&this.ctx)this.engineGain.gain.setTargetAtTime(0,this.ctx.currentTime,.04);this.voice?.pause();}
}
