import {Simulation,MAPS,terrainHeight,clamp,distance,forward} from './sim.js';
import {World} from './world.js';
import {Sound} from './audio.js';
const $=id=>document.getElementById(id),show=(id,value=true)=>$(id).classList.toggle('hidden',!value);
const STORE='sky-strike-flight-v1',PREFS='sky-strike-settings-v1',SCORES='sky-strike-records-v1';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d;}catch{return d;}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));}catch{}};
const names={hq:'КОМАНДНЫЙ ПУНКТ',sam:'ЗЕНИТНЫЙ КОМПЛЕКС',aa:'ЗЕНИТНАЯ УСТАНОВКА',radar:'РАДАР',fighter:'ИСТРЕБИТЕЛЬ',helicopter:'ВЕРТОЛЁТ'};
const voiceText={ready:'Бортовые системы готовы',altitude:'ВЫСОТА! НАБЕРИТЕ ВЫСОТУ',lock:'ОБНАРУЖЕНО ОБЛУЧЕНИЕ',missile:'РАКЕТНАЯ АТАКА · СБРОСЬТЕ ЛОВУШКИ',target:'Цель захвачена',destroyed:'Цель уничтожена',incoming:'Обнаружены воздушные цели',damage:'Повреждение самолёта',stall:'Недостаточная скорость',win:'Командные пункты уничтожены. Возвращайтесь к зелёному кольцу.',supply:'Самолёт восстановлен. Боезапас пополнен.',boundary:'ВЕРНИТЕСЬ В РАЙОН ОПЕРАЦИИ',empty:'Боезапас израсходован',flares:'Ловушки отстреляны'};
let world,sim,playing=false,paused=false,mapIndex=0,alertUntil=0,saveTimer=0,hudTimer=0,last=0,accumulator=0,boost=false,joystickPointer=null,joyX=0,joyY=0,gun=false,busy=false;
const sound=new Sound(),keys=new Set(),prefs=read(PREFS,{quality:'balanced',sound:true,difficulty:'easy'}),records=read(SCORES,{}),canvas=$('overlay'),ctx=canvas.getContext('2d'),radar=$('radar').getContext('2d');
let saved=read(STORE,null);
if(saved?.version!==1||!MAPS[saved?.mapIndex]||!['flying','returning'].includes(saved?.state?.status))saved=null;
function snapshot(){if(!sim||!playing||!['flying','returning'].includes(sim.status))return;const state={};for(const key of ['time','status','player','bases','entities','projectiles','nextId','kills','score','selected','mode','lock','baseDestroyed','missileTimer','gunTimer','flareTimer','flareActive','supplyTimer','outside'])state[key]=sim[key];saved={version:1,mapIndex:sim.map.id,difficulty:sim.difficulty,state};write(STORE,saved);}
function restore(data){const s=new Simulation(data.mapIndex,data.difficulty);Object.assign(s,data.state);s.contacts=[];s.events=[];s.radar();return s;}
function savePrefs(){prefs.quality=$('quality').value;prefs.difficulty=$('difficulty').value;prefs.sound=sound.enabled;write(PREFS,prefs);}
function clearInput(){keys.clear();gun=false;joyX=joyY=0;joystickPointer=null;$('knob').style.transform='';$('gun').classList.remove('active');}
function alert(key){const text=voiceText[key]||key;$('warning').textContent=text;$('warning').classList.toggle('danger',['missile','altitude','damage','boundary','stall'].includes(key));show('warning');alertUntil=performance.now()+(['missile','altitude'].includes(key)?3800:2800);}
function thumbnails(){for(const m of MAPS){const c=document.createElement('canvas');c.width=168;c.height=100;const x=c.getContext('2d'),im=x.createImageData(168,100);for(let y=0;y<100;y++)for(let i=0;i<168;i++){const h=terrainHeight(m,(i/168-.5)*33000,(y/100-.5)*33000),k=(y*168+i)*4,n=clamp(h/1700,0,1),water=h<0;const color=m.id===2?[92+n*91,62+n*82,49+n*59]:water?[35,85,100]:[45+n*112,68+n*104,68+n*87];im.data.set([...color,255],k);}x.putImageData(im,0,0);x.strokeStyle='#d1e6e525';x.lineWidth=.5;for(let i=0;i<168;i+=21){x.beginPath();x.moveTo(i,0);x.lineTo(i,100);x.stroke();}for(const b of m.bases){const px=(b.x/33000+.5)*168,py=(b.z/33000+.5)*100;x.strokeStyle='#ffbf9c';x.strokeRect(px-3,py-3,6,6);}const button=document.createElement('button');button.className='map-card';button.dataset.map=m.id;button.innerHTML=`<img alt="Карта района"><span><strong>${m.name}</strong><small>${m.area}</small></span><span class="number">0${m.id+1}</span>`;button.querySelector('img').src=c.toDataURL();button.onclick=()=>selectMap(m.id);$('maps').append(button);}}
function selectMap(index){if(busy)return;mapIndex=index;document.querySelectorAll('.map-card').forEach(e=>e.classList.toggle('active',+e.dataset.map===index));$('brief').textContent=MAPS[index].brief;sim=new Simulation(index,prefs.difficulty);sim.events=[];sim.player.y=terrainHeight(sim.map,sim.player.x,sim.player.z)+300;world.quality=$('quality').value;world.resize();world.build(sim);sim.time=14;}
async function start(resume=false){if(busy||!world)return;busy=true;show('loading');show('help-screen',false);await sound.start();savePrefs();await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);try{sim=resume&&saved?restore(saved):new Simulation(mapIndex,prefs.difficulty);mapIndex=sim.map.id;world.quality=prefs.quality;world.resize();world.build(sim);world.cameraMode=0;world.initialCamera=true;playing=true;paused=false;boost=false;clearInput();$('boost').classList.remove('active');$('throttle').value=Math.round(sim.player.throttle*100);$('mission-name').textContent=sim.map.name;for(const id of ['menu','result-screen','pause-screen'])show(id,false);show('hud');alertUntil=0;saveTimer=0;accumulator=0;snapshot();}catch(e){fatal(e);}finally{show('loading',false);busy=false;}}
function pause(){if(!playing||paused||!['flying','returning'].includes(sim.status))return;paused=true;clearInput();snapshot();sound.pause();show('pause-screen');}
function resume(){if(!playing)return;paused=false;last=performance.now();accumulator=0;clearInput();sound.start();show('pause-screen',false);}
function menu(){snapshot();playing=false;paused=false;clearInput();sound.pause();for(const id of ['hud','pause-screen','result-screen'])show(id,false);show('menu');show('resume',!!saved);show('warning',false);ctx.clearRect(0,0,innerWidth,innerHeight);selectMap(mapIndex);}
function result(event){snapshot();saved=null;try{localStorage.removeItem(STORE);}catch{};paused=true;clearInput();sound.pause();show('result-screen');$('result-title').textContent=event.win?'ЗАДАНИЕ ВЫПОЛНЕНО':'ВЫЛЕТ ПРЕРВАН';$('result-reason').textContent=event.reason;const mins=Math.floor(sim.time/60),secs=Math.floor(sim.time%60).toString().padStart(2,'0');$('result-stats').innerHTML=`<div><b>${sim.score}</b><small>ОЧКОВ</small></div><div><b>${sim.kills}</b><small>ЦЕЛЕЙ</small></div><div><b>${mins}:${secs}</b><small>ВРЕМЯ</small></div>`;records[sim.map.id]=Math.max(records[sim.map.id]||0,sim.score);write(SCORES,records);}
function fatal(e){console.error(e);$('fatal-text').textContent='Для игры требуется поддержка WebGL 2. Попробуйте закрыть другие приложения и запустить игру снова. '+String(e.message||e);show('fatal');}
function resize(){const ratio=Math.min(devicePixelRatio,1.5);canvas.width=Math.round(innerWidth*ratio);canvas.height=Math.round(innerHeight*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);world?.resize();}
function updateHud(){const p=sim.player,t=sim.target,alt=Math.max(0,sim.altitude);$('speed').textContent=Math.round(p.speed*3.6);$('altitude').textContent=Math.round(alt);$('asl').textContent=Math.round(p.y)+' М АБС.';$('g').textContent=p.g.toFixed(1)+' G';$('progress').textContent=`КОМАНДНЫЕ ПУНКТЫ ${sim.baseDestroyed} / 3`;$('health-label').textContent=`САМОЛЁТ ${Math.round(p.health)}%`;$('health-bar').style.width=p.health+'%';$('health-bar').style.background=p.health<35?'#f78c6d':'#a5e3cc';$('missile-count').textContent=p.missiles+' РАКЕТ';$('gun-count').textContent=p.gun;$('flare-count').textContent=p.flares;$('mode').textContent='РЕЖИМ: '+(sim.mode==='air'?'ВОЗДУХ':'ЗЕМЛЯ');$('radar-mode').textContent=sim.mode==='air'?'ВОЗДУХ':'ЗЕМЛЯ';$('throttle-label').textContent=Math.round(p.throttle*100)+'%';$('missile').classList.toggle('ready',sim.lock>=1&&p.missiles>0&&sim.missileTimer<=0);$('missile').disabled=sim.lock<1||p.missiles<=0||sim.missileTimer>0;$('flares').disabled=p.flares<=0||sim.flareTimer>0;$('lock-bar').style.width=(sim.lock*100)+'%';
 if(sim.status==='returning'){$('target-name').textContent='ВОЗВРАЩАЙТЕСЬ НА БАЗУ';$('target-detail').textContent=(distance(p,sim.resupply)/1000).toFixed(1)+' КМ ДО СНАБЖЕНИЯ';$('objective').textContent='ПРОЛЕТИТЕ ЧЕРЕЗ ЗЕЛЁНОЕ КОЛЬЦО';}else{$('target-name').textContent=t?names[t.type]:'ПОИСК ЦЕЛИ';$('target-detail').textContent=t?(distance(p,t)/1000).toFixed(1)+' КМ · '+(sim.lock===1?'ЗАХВАТ · ПУСК РАЗРЕШЁН':sim.canLock(t)?'ЗАХВАТ '+Math.round(sim.lock*100)+'%':'СОВМЕСТИТЕ ЦЕЛЬ С ПРИЦЕЛОМ'):'В ЭТОМ РЕЖИМЕ НЕТ КОНТАКТОВ';$('objective').textContent=sim.outside>0?'ДО ВЫХОДА ИЗ РАЙОНА: '+Math.ceil(16-sim.outside)+' С':'УНИЧТОЖЬТЕ КОМАНДНЫЕ ПУНКТЫ';}
 if(performance.now()>alertUntil)show('warning',false);
}
function drawRadar(){const c=radar,p=sim.player,cx=128,cy=120,r=106;c.clearRect(0,0,256,256);c.strokeStyle='#9dced332';c.lineWidth=1;for(const radius of [r/2,r]){c.beginPath();c.arc(cx,cy,radius,0,Math.PI*2);c.stroke();}c.beginPath();c.moveTo(cx,cy-r);c.lineTo(cx,cy+r);c.moveTo(cx-r,cy);c.lineTo(cx+r,cy);c.stroke();c.save();c.translate(cx,cy);c.rotate(sim.time*.9);const grad=c.createLinearGradient(0,0,0,-r);grad.addColorStop(0,'#a6ecd000');grad.addColorStop(1,'#a6ecd061');c.strokeStyle=grad;c.beginPath();c.moveTo(0,0);c.lineTo(0,-r);c.stroke();c.restore();const dot=(e,color,type,selected)=>{let dx=e.x-p.x,dz=e.z-p.z,x=(dx*Math.cos(p.yaw)-dz*Math.sin(p.yaw))/10500*r,y=-(dx*Math.sin(p.yaw)+dz*Math.cos(p.yaw))/10500*r;if(Math.hypot(x,y)>r)return;c.fillStyle=c.strokeStyle=color;c.lineWidth=1.5;if(type){c.beginPath();c.moveTo(cx+x,cy+y-4);c.lineTo(cx+x-4,cy+y+3);c.lineTo(cx+x+4,cy+y+3);c.closePath();c.fill();}else c.fillRect(cx+x-2.5,cy+y-2.5,5,5);if(selected)c.strokeRect(cx+x-7,cy+y-7,14,14);};
 for(const e of sim.contacts)dot(e,e.air?'#ffd09e':'#f7967e',e.air,e.id===sim.selected);for(const b of sim.bases)if(b.destroyed)dot(b,'#769d98',false,false);dot(sim.resupply,'#a4ebd1',false,true);for(const r of sim.projectiles)if(r.enemy)dot(r,'#ff5f40',true,false);c.fillStyle='#bde8e1';c.beginPath();c.moveTo(cx,cy-5);c.lineTo(cx-4,cy+5);c.lineTo(cx+4,cy+5);c.closePath();c.fill();c.fillStyle='#b9d7da';c.font='13px monospace';c.textAlign='center';c.fillText('▲',cx,12);c.font='10px monospace';c.fillText(Math.round((p.yaw*180/Math.PI+360)%360).toString().padStart(3,'0')+'°',cx,247);}
function drawHud(){const w=innerWidth,h=innerHeight,c=ctx,p=sim.player,f=forward(p.yaw,p.pitch),cross=world.project({x:p.x+f.x*5000,y:p.y+f.y*5000,z:p.z+f.z*5000});c.clearRect(0,0,w,h);c.lineWidth=1;c.strokeStyle='#c7f6dcb5';c.fillStyle='#ddf5de';c.font=(h<540?'10':'12')+'px monospace';c.textAlign='center';
 c.beginPath();c.arc(cross.x,cross.y,11,0,Math.PI*2);c.moveTo(cross.x-19,cross.y);c.lineTo(cross.x-7,cross.y);c.moveTo(cross.x+7,cross.y);c.lineTo(cross.x+19,cross.y);c.moveTo(cross.x,cross.y-19);c.lineTo(cross.x,cross.y-7);c.stroke();c.fillRect(cross.x-1,cross.y-1,2,2);
 const compassY=h<540?45:62,heading=(p.yaw*180/Math.PI+360)%360;for(let i=-3;i<=3;i++){const a=(Math.floor(heading/10)*10+i*10+360)%360,x=w/2+(i*10-heading%10)*4;c.strokeStyle='#cef0da65';c.beginPath();c.moveTo(x,compassY);c.lineTo(x,compassY+5);c.stroke();if(i%2===0)c.fillText(a.toString().padStart(3,'0'),x,compassY-5);}c.beginPath();c.moveTo(w/2-4,compassY+8);c.lineTo(w/2+4,compassY+8);c.lineTo(w/2,compassY+3);c.closePath();c.fill();
 c.save();c.translate(cross.x,cross.y);c.rotate(-p.roll*.35);c.globalAlpha=.45;for(let i=-2;i<=2;i++)if(i!==0){const y=i*33+p.pitch*40;c.beginPath();c.moveTo(-44,y);c.lineTo(-20,y);c.moveTo(20,y);c.lineTo(44,y);c.stroke();}c.restore();
 for(const e of sim.contacts){const screen=world.project(e),d=distance(p,e),chosen=e.id===sim.selected;if(!screen.visible||screen.x<8||screen.y<50||screen.x>w-8||screen.y>h-14)continue;if(!chosen&&d>7800)continue;const sz=chosen?20:7,x=screen.x,y=screen.y;c.strokeStyle=chosen?(sim.lock>=1?'#c2ffbd':'#ffe0a5'):'#e7aa83b3';c.lineWidth=chosen?1.6:1;if(chosen){for(const sx of [-1,1])for(const sy of [-1,1]){c.beginPath();c.moveTo(x+sx*sz,y+sy*(sz-7));c.lineTo(x+sx*sz,y+sy*sz);c.lineTo(x+sx*(sz-7),y+sy*sz);c.stroke();}c.fillStyle='#ffedc6';c.font=(h<540?'9':'11')+'px monospace';c.fillText(names[e.type],x,y-sz-9);c.fillText((d/1000).toFixed(1)+' КМ',x,y+sz+14);}else{c.save();c.translate(x,y);c.rotate(Math.PI/4);c.strokeRect(-sz/2,-sz/2,sz,sz);c.restore();}}
 const nav=world.project(sim.resupply);if(sim.status==='returning'||distance(p,sim.resupply)<4000){let x=clamp(nav.x,35,w-35),y=clamp(nav.y,75,h-90);if(!nav.visible){const a=Math.atan2(sim.resupply.x-p.x,sim.resupply.z-p.z)-p.yaw;x=w/2+Math.sin(a)*(w*.34);y=h*.3;}c.strokeStyle=c.fillStyle='#a8ffe0';c.beginPath();c.arc(x,y,13,0,Math.PI*2);c.stroke();c.font='10px monospace';c.fillText('СНАБЖЕНИЕ '+(distance(p,sim.resupply)/1000).toFixed(1)+' КМ',x,y-20);}
 if(sim.flareActive>0){c.fillStyle='#f9ddb0';c.font='10px monospace';c.fillText('ЛОВУШКИ АКТИВНЫ',w/2,h*.68);}
}
function frame(now){const delta=Math.min((now-last)/1000||.016,.1);last=now;try{if(world&&sim){if(playing&&!paused){const input={x:clamp(joyX+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),-1,1),y:clamp(joyY+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0),-1,1),throttle:+$('throttle').value/100,boost:boost||keys.has('ShiftLeft')||keys.has('ShiftRight'),gun:gun||keys.has('Space')};accumulator+=delta;let n=0;while(accumulator>=1/60&&n++<7){sim.update(1/60,input);accumulator-=1/60;}for(const event of sim.drain()){if(event.type==='voice'){sound.speak(event.data);alert(event.data);}if(['gun','launch','explosion','flares'].includes(event.type)){world.effect(event);sound.effect(event.type);}if(event.type==='hit')world.effect(event);if(event.type==='damage'){$('damage').style.opacity='.7';setTimeout(()=>$('damage').style.opacity='0',150);}if(event.type==='result')result(event.data);}world.update(sim,delta,false,input.boost);sound.update(sim.player,true,input.boost);hudTimer+=delta;if(hudTimer>.08){updateHud();drawRadar();hudTimer=0;}drawHud();saveTimer+=delta;if(saveTimer>4){snapshot();saveTimer=0;}}else if(!playing&&!busy){sim.time+=delta;world.update(sim,delta,true,true);}else if(playing){sound.pause();}}}catch(e){fatal(e);paused=true;}requestAnimationFrame(frame);}
function bindHold(id,on,off){const b=$(id);b.addEventListener('pointerdown',e=>{if(!playing||paused)return;e.preventDefault();b.setPointerCapture(e.pointerId);on();b.classList.add('active');});for(const kind of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(kind,()=>{off();b.classList.remove('active');});}
$('stick').addEventListener('pointerdown',e=>{if(!playing||paused||joystickPointer!==null)return;joystickPointer=e.pointerId;$('stick').setPointerCapture(e.pointerId);moveStick(e);});
function moveStick(e){if(e.pointerId!==joystickPointer)return;const r=$('stick').getBoundingClientRect(),radius=r.width*.36;let x=(e.clientX-r.left-r.width/2)/radius,y=(e.clientY-r.top-r.height/2)/radius,n=Math.max(1,Math.hypot(x,y));joyX=x/n;joyY=y/n;$('knob').style.transform=`translate(${joyX*radius}px,${joyY*radius}px)`;}
$('stick').addEventListener('pointermove',moveStick);for(const k of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(k,e=>{if(e.pointerId===joystickPointer){joystickPointer=null;joyX=joyY=0;$('knob').style.transform='';}});
bindHold('gun',()=>gun=true,()=>gun=false);
$('start').onclick=()=>start(false);$('resume').onclick=()=>start(true);$('pause').onclick=pause;$('continue').onclick=resume;$('exit').onclick=menu;$('restart').onclick=()=>start(false);$('again').onclick=()=>start(false);$('result-menu').onclick=menu;$('help').onclick=()=>show('help-screen');$('close-help').onclick=()=>show('help-screen',false);
$('target').onclick=()=>sim?.selectNext();$('mode').onclick=()=>sim?.toggleMode();$('missile').onclick=()=>sim?.launch();$('flares').onclick=()=>sim?.flares();$('camera').onclick=()=>{world.cameraMode=1-world.cameraMode;world.initialCamera=true;};$('boost').onclick=()=>{boost=!boost;$('boost').classList.toggle('active',boost);};
$('difficulty').value=prefs.difficulty;$('quality').value=prefs.quality;sound.enabled=prefs.sound;$('sound').textContent=sound.enabled?'ЗВУК ВКЛ':'ЗВУК ВЫКЛ';$('sound').onclick=()=>{sound.enabled=!sound.enabled;$('sound').textContent=sound.enabled?'ЗВУК ВКЛ':'ЗВУК ВЫКЛ';if(!sound.enabled)sound.pause();savePrefs();};$('quality').onchange=()=>{savePrefs();if(!playing)selectMap(mapIndex);};$('difficulty').onchange=savePrefs;
window.addEventListener('keydown',e=>{if(!playing)return;if(['Tab','Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){paused?resume():pause();return;}if(paused)return;keys.add(e.code);if(e.repeat)return;if(e.code==='Enter')sim.launch();if(e.code==='KeyF')sim.flares();if(e.code==='Tab')sim.selectNext();if(e.code==='KeyR')sim.toggleMode();if(e.code==='KeyC')$('camera').click();});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('resize',resize);document.addEventListener('contextmenu',e=>e.preventDefault());
window.Game={get sim(){return sim;},get world(){return world;},get playing(){return playing;},get paused(){return paused;},start,pause,resume,menu,snapshot,selectMap,get status(){return{ready:!!world,playing,paused,map:sim?.map.id,status:sim?.status,health:sim?.player.health,altitude:sim?.altitude,targets:sim?.entities.length,webgl:!!world?.renderer.getContext(),version:'0.1.0'};}};
try{world=new World($('world'));thumbnails();selectMap(0);show('resume',!!saved);resize();window.__gameReady=true;requestAnimationFrame(frame);}catch(e){fatal(e);}
