import * as T from 'three';
import {terrainHeight,noise,clamp} from './sim.js';
const Y=new T.Vector3(0,1,0);
const mat=(color,extra={})=>new T.MeshPhongMaterial({color,shininess:24,...extra});
function mesh(g,m,x=0,y=0,z=0){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;return o;}
function box(g,m,s,x=0,y=0,z=0){const o=mesh(new T.BoxGeometry(...s),m,x,y,z);g.add(o);return o;}
function plate(points,material){const shape=new T.Shape();points.forEach(([x,z],i)=>i?shape.lineTo(x,z):shape.moveTo(x,z));shape.closePath();const geo=new T.ExtrudeGeometry(shape,{depth:.17,bevelEnabled:false});geo.rotateX(Math.PI/2);const o=mesh(geo,material);return o;}
function fuselage(material){const sections=[[-9,1.9,.65],[-6,3,1],[-1,2.8,1.25],[3,1.8,1],[6.4,.82,.55],[10.2,.015,.02]],v=[],idx=[];for(const [z,w,h]of sections)for(let i=0;i<8;i++){let a=i*Math.PI/4;v.push(Math.cos(a)*w,Math.sin(a)*h,z);}for(let j=0;j<sections.length-1;j++)for(let i=0;i<8;i++){const a=j*8+i,b=j*8+(i+1)%8,c=a+8,d=b+8;idx.push(a,b,c,b,d,c);}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(v,3));geo.setIndex(idx);geo.computeVertexNormals();return mesh(geo,material);}
export function jet(enemy=false,detail=true){const g=new T.Group(),metal=mat(enemy?0x827f75:0x8597a1,{shininess:46}),dark=mat(0x26333e),edge=mat(0x657a87,{side:T.DoubleSide}),canopy=mat(0x132b39,{shininess:120,specular:0xa4d7e8}),hot=new T.MeshBasicMaterial({color:0xff9c50,transparent:true,opacity:.9});
 g.add(fuselage(metal));
 for(const side of [-1,1]){
  const wing=plate([[side*1.3,3],[side*7.2,-2.8],[side*7.3,-5.1],[side*2,-4.8]],metal);g.add(wing);
  const tail=plate([[side*2,-5.7],[side*5.2,-7.2],[side*5.1,-9.1],[side*1.8,-8.6]],edge);g.add(tail);
  const finGeo=new T.BufferGeometry();finGeo.setAttribute('position',new T.Float32BufferAttribute([side*2.15,.3,-8.5,side*3,3.5,-7.4,side*2.8,3.45,-5.9,side*2.1,.3,-4.9],3));finGeo.setIndex([0,1,2,0,2,3]);finGeo.computeVertexNormals();g.add(mesh(finGeo,edge));
  const engine=mesh(new T.CylinderGeometry(.77,.92,7,12),dark,side*1.6,-.7,-5.3);engine.rotation.x=Math.PI/2;g.add(engine);
  g.add(mesh(new T.TorusGeometry(.78,.17,6,16),metal,side*1.6,-.7,-8.95));
  const nozzle=mesh(new T.CircleGeometry(.66,16),hot,side*1.6,-.7,-9.01);nozzle.rotation.y=Math.PI;g.add(nozzle);
  const flame=mesh(new T.ConeGeometry(.67,4.5,12),new T.MeshBasicMaterial({color:0x79caff,transparent:true,opacity:.62,depthWrite:false}),side*1.6,-.7,-11);flame.rotation.x=-Math.PI/2;flame.castShadow=false;g.add(flame);(g.userData.flames??=[]).push(flame);
  if(detail){const seam=new T.LineSegments(new T.EdgesGeometry(wing.geometry,25),new T.LineBasicMaterial({color:0x22313c,transparent:true,opacity:.32}));wing.add(seam);box(g,enemy?mat(0x9d4a3f):mat(0xc9d8df),[1.5,.03,.45],side*4.3,.2,-2.5);}
 }
 const glass=mesh(new T.SphereGeometry(1,16,10),canopy,0,1.05,3.6);glass.scale.set(.77,.68,1.9);g.add(glass);box(g,dark,[.07,.85,.1],0,1.34,4);
 g.userData.aircraft=true;return g;
}
export function helicopter(){const g=new T.Group(),body=mat(0x707664),dark=mat(0x243535);const f=mesh(new T.SphereGeometry(1,12,8),body,0,0,1);f.scale.set(2.9,2.6,6);g.add(f);const glass=mesh(new T.SphereGeometry(1,12,8),mat(0x233b49,{shininess:90}),0,.4,4.3);glass.scale.set(2.5,1.9,2.5);g.add(glass);const tail=mesh(new T.ConeGeometry(1.15,12,8),body,0,.4,-9);tail.rotation.x=-Math.PI/2;g.add(tail);box(g,body,[.35,4,2],0,2,-14);for(let s of [-1,1])box(g,dark,[.35,.35,10],s*2,-3,0);box(g,dark,[.55,3,.55],0,3,0);const rotor=new T.Group();rotor.position.y=4.2;box(rotor,dark,[20,.12,.5]);box(rotor,dark,[.5,.12,20]);g.add(rotor);g.userData.rotor=rotor;return g;}
function groundUnit(type){const g=new T.Group(),metal=mat(0x556353),dark=mat(0x222b28),light=mat(0xabb5a6);if(type==='hq'){box(g,mat(0x97988d),[75,25,54],0,0,0);box(g,mat(0x5f6966),[82,3,60],0,14,0);for(let i=0;i<5;i++){box(g,dark,[9,7,.3],-29+i*14,2,27.2);box(g,mat(0xb55d4d),[9,1,.5],-29+i*14,9,27.6);}box(g,metal,[18,13,18],0,21,0);box(g,dark,[.8,24,.8],0,40,0);}else if(type==='radar'){box(g,metal,[20,9,17],0,0,0);box(g,dark,[2,32,2],0,19,0);const antenna=new T.Group();antenna.position.y=37;const dish=mesh(new T.SphereGeometry(14,14,6,0,Math.PI*2,0,Math.PI/2),light);dish.rotation.x=Math.PI/2;dish.scale.y=.28;antenna.add(dish);box(antenna,dark,[1,10,1],0,3,2);g.add(antenna);g.userData.rotor=antenna;}else{box(g,metal,[9,6,20],0,-3,0);for(let s of [-1,1])box(g,dark,[2,4,20],s*5,-6,0);const turret=new T.Group();if(type==='sam'){for(let s of [-1,1])for(let z of [-1,1]){const tube=mesh(new T.CylinderGeometry(1.4,1.4,14,8),light,s*2.1,4,z*2);tube.rotation.x=.78;turret.add(tube);}}else{box(turret,metal,[8,5,8],0,2,0);for(let s of [-1,1]){const barrel=mesh(new T.CylinderGeometry(.5,.6,12,6),dark,s*2,5,5);barrel.rotation.x=.92;turret.add(barrel);}}g.add(turret);g.userData.turret=turret;}return g;}
function noiseTexture(){const c=document.createElement('canvas');c.width=c.height=256;const cx=c.getContext('2d'),im=cx.createImageData(256,256);for(let i=0;i<im.data.length;i+=4){const n=195+Math.random()*55;im.data[i]=im.data[i+1]=im.data[i+2]=n;im.data[i+3]=255;}cx.putImageData(im,0,0);const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(180,180);return t;}
const skyVertex=`varying vec3 vDir;void main(){vDir=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`;
const skyFragment=`varying vec3 vDir;uniform vec3 low;uniform vec3 high;uniform vec3 sun;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}void main(){vec3 d=normalize(vDir);float h=max(0.,d.y);vec3 c=mix(low,high,sqrt(h));float s=max(0.,dot(d,normalize(sun)));c+=vec3(1.,.83,.59)*(pow(s,800.)*2.2+pow(s,28.)*.16);vec2 uv=d.xz/max(.12,d.y+.08)*1.5;float f=n(uv)*.55+n(uv*2.2)*.27+n(uv*5.1)*.12+n(uv*10.)*.06;float cl=smoothstep(.55,.76,f)*smoothstep(.02,.23,h);c=mix(c,vec3(.94,.95,.96),cl*.78);gl_FragColor=vec4(c,1.);}`;

export class World{
 constructor(canvas){this.canvas=canvas;this.renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.14;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.camera=new T.PerspectiveCamera(57,1,1,70000);this.effects=[];this.entityMeshes=new Map();this.rocketMeshes=new Map();this.cameraMode=0;this.quality='balanced';this.temp=new T.Vector3();this.initialCamera=true;this.resize();}
 resize(){const w=innerWidth,h=innerHeight;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.quality==='high'?1.5:this.quality==='low'?.8:1.1));this.renderer.setSize(w,h,false);this.renderer.shadowMap.enabled=this.quality!=='low';}
 disposeScene(){if(!this.scene)return;const geos=new Set(),mats=new Set(),textures=new Set();this.scene.traverse(o=>{if(o.geometry)geos.add(o.geometry);for(const m of(Array.isArray(o.material)?o.material:o.material?[o.material]:[])){mats.add(m);if(m.map)textures.add(m.map);}});for(const g of geos)g.dispose();for(const m of mats)m.dispose();for(const t of textures)t.dispose();}
 build(sim){this.disposeScene();this.sim=sim;this.scene=new T.Scene();this.scene.fog=new T.Fog(sim.map.fog,6500,23000);this.effects=[];this.entityMeshes.clear();this.rocketMeshes.clear();this.initialCamera=true;const m=sim.map;
  this.scene.add(new T.HemisphereLight(0xd4e9fa,0x5b554c,2));this.sun=new T.DirectionalLight(m.sun,2.8);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);Object.assign(this.sun.shadow.camera,{left:-220,right:220,top:220,bottom:-220,near:5,far:2800});this.sun.shadow.bias=-.0003;this.sun.shadow.normalBias=1;this.scene.add(this.sun,this.sun.target);
  this.sky=mesh(new T.SphereGeometry(36000,28,16),new T.ShaderMaterial({uniforms:{low:{value:new T.Color(m.fog)},high:{value:new T.Color(m.sky).multiplyScalar(.7)},sun:{value:new T.Vector3(-.5,.6,-.4)}},vertexShader:skyVertex,fragmentShader:skyFragment,side:T.BackSide,depthWrite:false}));this.sky.castShadow=false;this.sky.receiveShadow=false;this.sky.renderOrder=-2;this.scene.add(this.sky);
  const seg=this.quality==='low'?180:256,geo=new T.PlaneGeometry(34000,34000,seg,seg);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position,col=new Float32Array(pos.count*3),green=new T.Color(),a=new T.Color(m.id===2?0xa7754f:0x6e7552),b=new T.Color(m.id===2?0xc2996c:0x344c3c),rock=new T.Color(m.id===2?0x775541:0x88928b);
  for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),h=terrainHeight(m,x,z);pos.setY(i,h);const n=noise(x/420,z/420,m.seed);green.copy(a).lerp(b,n);if(m.id!==2&&h>850)green.lerp(rock,clamp((h-850)/700,0,.85));if(m.id===0&&h>1350)green.lerp(new T.Color(0xdce2df),clamp((h-1350)/300,0,.95));if(m.id===1&&h<60)green.set(0xb5b293);if(m.id===2)green.multiplyScalar(.83+.17*Math.sin(h*.07));col.set([green.r,green.g,green.b],i*3);}
  geo.setAttribute('color',new T.BufferAttribute(col,3));geo.computeVertexNormals();const land=mesh(geo,mat(0xffffff,{vertexColors:true,shininess:2,map:noiseTexture()}));land.castShadow=false;this.scene.add(land);
  this.water=mesh(new T.PlaneGeometry(80000,80000),mat(m.water,{shininess:85,specular:0x7a9fae,transparent:true,opacity:.96}));this.water.rotation.x=-Math.PI/2;this.water.position.y=1;this.water.castShadow=false;this.scene.add(this.water);
  if(m.id!==2)this.trees(m);
  for(const base of [...sim.bases,{...m.start,id:0,y:terrainHeight(m,m.start.x,m.start.z)}])this.baseScenery(base);
  this.player=jet(false,true);this.scene.add(this.player);for(const e of sim.entities)this.addEntity(e);
  const ring=mesh(new T.TorusGeometry(240,7,6,64),new T.MeshBasicMaterial({color:0x72ebc2,transparent:true,opacity:.6}));ring.position.set(sim.resupply.x,sim.resupply.y,sim.resupply.z);ring.castShadow=false;this.scene.add(ring);this.supplyRing=ring;
 }
 trees(m){const count=this.quality==='low'?750:2100,geo=new T.ConeGeometry(1,1,5),leaves=new T.InstancedMesh(geo,mat(0x304b3e,{shininess:0}),count),trunks=new T.InstancedMesh(new T.CylinderGeometry(.08,.1,.55,4),mat(0x695b49),count),dummy=new T.Object3D();let used=0;for(let i=0;used<count&&i<count*12;i++){const x=(noise(i*13.71,1,m.seed)-.5)*31500,z=(noise(4,i*11.32,m.seed+7)-.5)*31500,h=terrainHeight(m,x,z);if(h<25||h>1100||[...m.bases,m.start].some(b=>Math.hypot(x-b.x,z-b.z)<600))continue;const size=24+noise(i*1.2,i*2.3,m.seed)*22;dummy.position.set(x,h+size*.52,z);dummy.scale.set(size*.38,size,size*.38);dummy.rotation.set(0,i*1.8,0);dummy.updateMatrix();leaves.setMatrixAt(used,dummy.matrix);dummy.position.y=h+size*.2;dummy.updateMatrix();trunks.setMatrixAt(used,dummy.matrix);used++;}leaves.count=trunks.count=used;leaves.receiveShadow=true;this.scene.add(leaves,trunks);}
 baseScenery(b){const g=new T.Group(),concrete=mat(b.id?0x747d78:0x697b80),dark=mat(0x303a3c),building=mat(0x92988c);g.position.set(b.x,b.y,b.z);box(g,concrete,[650,2,650],0,1,0);box(g,dark,[72,2,540],280,3,0);for(let i=0;i<12;i++)box(g,mat(0xd9ddca),[2,.3,15],280,4.2,-240+i*43);for(let i=0;i<4;i++){const hangar=box(g,building,[70,26,75],-80+i*92,15,-270);box(g,dark,[55,19,1],-80+i*92,12,-231.8);box(g,mat(0x5e716a),[74,3,79],-80+i*92,30,-270);}for(let i=0;i<4;i++){const silo=mesh(new T.CylinderGeometry(15,15,26,12),concrete,-270,14,-180+i*50);g.add(silo);}this.scene.add(g);}
 addEntity(e){const g=e.air?(e.type==='fighter'?jet(true,false):helicopter()):groundUnit(e.type);g.position.set(e.x,e.y,e.z);this.scene.add(g);this.entityMeshes.set(e.id,g);return g;}
 effect(event){const data=event.data;if(event.type==='gun'){const geo=new T.BufferGeometry().setFromPoints([new T.Vector3(data.from.x,data.from.y,data.from.z),new T.Vector3(data.to.x,data.to.y,data.to.z)]),o=new T.Line(geo,new T.LineBasicMaterial({color:data.enemy?0xff7850:0xffeabb,transparent:true,opacity:.9}));this.scene.add(o);this.effects.push({o,life:.075,total:.075,type:'line'});}
  if(event.type==='explosion'||event.type==='hit'){const size=data.size||8;const o=mesh(new T.IcosahedronGeometry(1,1),new T.MeshBasicMaterial({color:0xffb051,transparent:true,opacity:.9,depthWrite:false}));o.position.set(data.x,data.y,data.z);o.castShadow=false;this.scene.add(o);this.effects.push({o,life:event.type==='hit'?.18:1.2,total:event.type==='hit'?.18:1.2,size,type:'fire'});for(let i=0;i<(event.type==='hit'?0:8);i++){const p=mesh(new T.IcosahedronGeometry(size*.24,0),new T.MeshBasicMaterial({color:0x5d5146,transparent:true,opacity:.55,depthWrite:false}));p.position.copy(o.position);p.castShadow=false;this.scene.add(p);this.effects.push({o:p,life:3.5,total:3.5,v:new T.Vector3((Math.random()-.5)*size,20+Math.random()*size*.4,(Math.random()-.5)*size),type:'smoke'});}}
  if(event.type==='flares')for(let i=0;i<12;i++){const o=mesh(new T.SphereGeometry(1.5,6,4),new T.MeshBasicMaterial({color:0xffe7a3}));o.position.set(data.x,data.y,data.z);this.scene.add(o);this.effects.push({o,life:3,total:3,v:new T.Vector3((Math.random()-.5)*110,-20-Math.random()*30,(Math.random()-.5)*70),type:'flare'});}
 }
 update(sim,dt,menu=false,boost=false){const p=sim.player,f=new T.Vector3(Math.sin(p.yaw)*Math.cos(p.pitch),Math.sin(p.pitch),Math.cos(p.yaw)*Math.cos(p.pitch)),pp=new T.Vector3(p.x,p.y,p.z);this.player.position.copy(pp);this.player.lookAt(pp.clone().add(f));this.player.rotateZ(-p.roll);this.player.visible=this.cameraMode===0||menu;for(const flame of this.player.userData.flames){flame.visible=boost||menu;flame.scale.y=1+Math.sin(sim.time*35)*.1;}
  let desired,look;if(menu){const angle=sim.time*.055;desired=pp.clone().add(new T.Vector3(Math.sin(angle)*31,10,Math.cos(angle)*31));look=pp.clone().add(new T.Vector3(0,0,0));}else if(this.cameraMode===0){desired=pp.clone().addScaledVector(f,-70).add(new T.Vector3(0,21,0));look=pp.clone().addScaledVector(f,650).add(new T.Vector3(0,5,0));}else{desired=pp.clone().add(new T.Vector3(0,1.8,0)).addScaledVector(f,5);look=desired.clone().addScaledVector(f,1500);}
  this.camera.position.lerp(desired,this.initialCamera?1:1-Math.exp(-dt*7));this.initialCamera=false;this.camera.up.copy(Y);if(this.cameraMode===1&&!menu)this.camera.up.applyAxisAngle(f,-p.roll*.92);this.camera.lookAt(look);this.sky.position.copy(this.camera.position);this.sun.position.copy(pp).add(new T.Vector3(-900,1300,-700));this.sun.target.position.copy(pp);
  for(const e of sim.entities){let g=this.entityMeshes.get(e.id)||this.addEntity(e);if(!e.alive){g.visible=false;continue;}g.visible=true;g.position.set(e.x,e.y,e.z);if(e.air){const dir=new T.Vector3(Math.sin(e.yaw),Math.sin(e.pitch),Math.cos(e.yaw));g.lookAt(g.position.clone().add(dir));if(e.type==='fighter')g.rotateZ(e.roll);}if(g.userData.rotor)g.userData.rotor.rotation.y+=dt*(e.air?31:1.1);if(g.userData.turret)g.userData.turret.rotation.y=Math.atan2(p.x-e.x,p.z-e.z);}
  for(const [id,o]of this.rocketMeshes)if(!sim.projectiles.some(r=>r.id===id)){this.scene.remove(o);o.geometry.dispose();o.material.dispose();this.rocketMeshes.delete(id);}
  for(const r of sim.projectiles){let o=this.rocketMeshes.get(r.id);if(!o){o=mesh(new T.ConeGeometry(r.kind==='bullet'?1.5:1.4,r.kind==='bullet'?10:14,6),new T.MeshBasicMaterial({color:r.enemy?0xff624b:0xf7e7bc}));o.castShadow=false;this.scene.add(o);this.rocketMeshes.set(r.id,o);}o.position.set(r.x,r.y,r.z);o.quaternion.setFromUnitVectors(Y,new T.Vector3(r.vx,r.vy,r.vz).normalize());}
  for(const e of this.effects){e.life-=dt;if(e.type==='fire'){const a=1-e.life/e.total;e.o.scale.setScalar(e.size*(.3+a*1.3));e.o.material.opacity=Math.max(0,1-a);e.o.material.color.lerp(new T.Color(0xb14422),dt*2);}else if(e.v){e.o.position.addScaledVector(e.v,dt);if(e.type==='smoke')e.o.scale.multiplyScalar(1+dt*.3);e.o.material.opacity=clamp(e.life/e.total,0,.6);}}
  this.effects=this.effects.filter(e=>{if(e.life>0)return true;this.scene.remove(e.o);e.o.geometry.dispose();e.o.material.dispose();return false;});
  this.supplyRing.rotation.y=sim.time*.25;this.renderer.render(this.scene,this.camera);
 }
 project(pos){const p=new T.Vector3(pos.x,pos.y,pos.z).project(this.camera);return{x:(p.x*.5+.5)*innerWidth,y:(-p.y*.5+.5)*innerHeight,visible:p.z<1&&p.z>-1};}
}
